name: Build SystemWebView

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-arm64:
    name: Build arm64 SystemWebView
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: Clean space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          root-reserve-mb: 1536
          swap-size-mb: 2048
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install CCache
        run: |
          sudo apt-get update && sudo apt-get install -y ccache

      - name: Initialize CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-arm64-${{ github.sha }}
          restore-keys: ccache-arm64-
          max-size: 5G

      - name: Set up Cromite Tools
        run: |
          chmod -R +x tools/

      - name: Set up Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
          gclient

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone Chromium
        run: |
          mkdir chromium/
          cd chromium/
        
          fetch --nohooks --no-history android

          cd src/

          git config --unset-all remote.origin.fetch || true
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          rm -rf .git/refs/tags/refs || true

          git fetch origin tag refs/tags/${{ github.ref_name }}:refs/tags/${{ github.ref_name }} --depth 1
          git checkout tags/${{ github.ref_name }}

      - name: Init Environment
        run: |
          cd chromium/src/

          gclient sync -j$(nproc) --with_branch_heads --with_tags --force --reset --no-history

          cd ..

          mv src/ ..

          cd ..

          rm -rf chromium/

      - name: Install Dependencies
        run: |
          sudo bash src/build/install-build-deps.sh --no-prompt --no-chromeos-fonts --android

      - name: Apply Patches
        run: |
          tools/apply-all-patch.sh

      - name: Configure Arguments
        run: |
          cd src/
          
          mkdir -p out/Default
          
          echo 'target_os = "android"' > out/Default/args.gn
          echo 'target_cpu = "arm64"' >> out/Default/args.gn
          echo 'is_debug = false' >> out/Default/args.gn
          echo 'is_official_build = true' >> out/Default/args.gn
          echo 'cc_wrapper = "ccache"' >> out/Default/args.gn

      - name: Build SystemWebView
        run: |
          cd src/
          
          autoninja -C out/Default system_webview_apk

      - name: Rename SystemWebView.apk
        run: |
          mv src/out/Default/apks/SystemWebView.apk src/out/Default/apks/arm64-SystemWebView.apk

      - name: Upload SystemWebView.apk arm64
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'test') }}
          files: src/out/Default/apks/arm64-SystemWebView.apk
  
  build-x64:
    name: Build x64 WebView
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: Clean space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          root-reserve-mb: 1536
          swap-size-mb: 2048
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install CCache
        run: |
          sudo apt-get update && sudo apt-get install -y ccache

      - name: Initialize CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-x64-${{ github.sha }}
          restore-keys: ccache-x64-
          max-size: 5G

      - name: Set up Cromite Tools
        run: |
          chmod -R +x tools/

      - name: Set up Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
          gclient

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone Chromium
        run: |
          mkdir chromium/
          cd chromium/
          
          fetch --nohooks --no-history android

          cd src/

          git config --unset-all remote.origin.fetch || true
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          rm -rf .git/refs/tags/refs || true

          git fetch origin tag refs/tags/${{ github.ref_name }}:refs/tags/${{ github.ref_name }} --depth 1
          git checkout tags/${{ github.ref_name }}

      - name: Init Environment
        run: |
          cd chromium/src/

          gclient sync -j$(nproc) --with_branch_heads --with_tags --force --reset --no-history

          cd ..

          mv src/ ..

          cd ..

          rm -rf chromium/

      - name: Install Dependencies
        run: |
          sudo bash src/build/install-build-deps.sh --no-prompt --no-chromeos-fonts --android

      - name: Apply Patches
        run: |
          tools/apply-all-patch.sh

      - name: Configure Arguments
        run: |
          cd src/
          
          mkdir -p out/Default
          
          echo 'target_os = "android"' > out/Default/args.gn
          echo 'target_cpu = "x64"' >> out/Default/args.gn
          echo 'is_debug = false' >> out/Default/args.gn
          echo 'is_official_build = true' >> out/Default/args.gn
          echo 'cc_wrapper = "ccache"' >> out/Default/args.gn

      - name: Compile SystemWebView
        run: |
          cd src/
          
          autoninja -C out/Default system_webview_apk

      - name: Rename SystemWebView.apk
        run: |
          mv src/out/Default/apks/SystemWebView.apk src/out/Default/apks/x64-SystemWebView.apk

      - name: Upload SystemWebView.apk x64
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'test') }}
          files: src/out/Default/apks/x64-SystemWebView.apk
