name: Sync

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  sync:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync w Upstream
        id: sync-upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with: 
          upstream_sync_repo: 'uazo/cromite'
          upstream_sync_branch: 'master'
          target_sync_branch: 'master'
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
